# Generated by Django 4.0.2 on 2022-02-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_apis', '0003_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp']},
        ),
    ]
