# Generated by Django 4.0.2 on 2022-02-07 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restful_apis', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='accepter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
